version: '1.0'

services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tour
      MYSQL_USER: tour
      MYSQL_PASSWORD: 123456
    ports:
      - 3307:3306
    volumes:
      - vol-mysql:/var/lib/mysql

volumes:
  vol-mysql: